<a href="https://colab.research.google.com/github/maqsud1987/JS-darslarim/blob/main/Pandas_bilan_tanishuv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from pandas import Series # series ma'lumotlar tuzilmasi

obj = Series([4, 5, 6, -6.7])
print(obj)

0    4.0
1    5.0
2    6.0
3   -6.7
dtype: float64

In [ ]:
obj.values

array([ 4. ,  5. ,  6. , -6.7])

In [ ]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [ ]:
obj2 = Series([4, 5, 6, -6.7], index=['a', 'b', 'c', 'd'])
obj2

a    4.0
b    5.0
c    6.0
d   -6.7
dtype: float64

In [ ]:
obj2

a    4.0
b    5.0
c    6.0
d   -6.7
dtype: float64

In [ ]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [ ]:
obj2['d']

np.float64(-6.7)

In [ ]:
obj2[obj2>2]

a    4.0
b    5.0
c    6.0
dtype: float64

In [ ]:
cars_dictionary = {'Malibu':40000, 'Lacetti':20000, 'Toyota':10000, 'Mazda':5000}
cars = Series(cars_dictionary)
cars

Malibu     40000
Lacetti    20000
Toyota     10000
Mazda       5000
dtype: int64

In [ ]:
cars_dictionary = {'Malibu':40000, 'Lacetti':20000, 'Toyota':10000, 'Mazda':5000}
cars = Series(cars_dictionary)
cars

Malibu     40000
Lacetti    20000
Toyota     10000
Mazda       5000
dtype: int64

In [ ]:
cars_dictionary = {'Malibu':40000, 'Lacetti':20000, 'Toyota':10000, 'Mazda':5000}
cars = Series(cars_dictionary)
cars

Malibu     40000
Lacetti    20000
Toyota     10000
Mazda       5000
dtype: int64

In [ ]:
cars_dictionary = {'Malibu':40000, 'Lacetti':20000, 'Toyota':10000, 'Mazda':5000}
cars = Series(cars_dictionary)
cars

Malibu     40000
Lacetti    20000
Toyota     10000
Mazda       5000
dtype: int64

In [ ]:
"Malibu" in cars_dictionary

True

In [ ]:
'Malibu' in cars

True

In [ ]:
cars1 = Series({'Malibu':40000, 'Lacetti':20000, 'Toyota':10000, 'Mazda':5000})
cars1

Malibu     40000
Lacetti    20000
Toyota     10000
Mazda       5000
dtype: int64

In [ ]:
'Toyota' in  cars1

True

In [ ]:
'BMW' in cars1

False

In [ ]:
models = ['Honda', 'Mazda', 'Lacetti', 'Jaguar', 'Malibu', 'Toyota''Chevrolet','Lada']
cars2 = Series(cars_dictionary, index=models)
cars2

Honda                  NaN
Mazda               5000.0
Lacetti            20000.0
Jaguar                 NaN
Malibu             40000.0
ToyotaChevrolet        NaN
Lada                   NaN
dtype: float64